---

- name: Install snapd
  dnf:
    name: ['snapd']
    state: present
    update_cache: True


- name: Link snaps to classic envirnment 
  file: 
    src: /var/lib/snapd/snap
    dest: /snap
    state: link