---

- name: Add Sublime Merge Key
  rpm_key:
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    state: present

- name: Prepare Sublime Merge
  command: dnf config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo

- name: Install Sublime Merge
  dnf:
    name: ['sublime-merge']
    state: present
    update_cache: True